[package]
name = "rushdrop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
askama = "0.16"
axum = { version = "0.8", features = ["multipart"] }
axum-server = { version = "0.8", features = ["tls-rustls"] }
clap = { version = "4", features = ["derive"] }
dirs = "6"
dunce = "1"
enable-ansi-support = "0.3"
futures = "0.3"
image = { version = "0.25", features = ["jpeg", "png", "gif", "webp"] }
libheif-rs = { version = "2.7.0" }
local-ip-address = "0.6"
mime_guess = "2"
multer = "3.1"
qr2term = "0.3"
rcgen = "0.14"
sanitize-filename = "0.6"
serde_json = "1"
supports-color = "3"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.7", features = ["fs", "limit", "timeout"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

[profile.release]
lto = "fat"
codegen-units = 1